FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

# Instalar Ghostscript
RUN apt-get update && apt-get install -y ghostscript && rm -rf /var/lib/apt/lists/*

# Copiar el código
COPY . .

CMD ["dotnet", "run", "--project", "PdfReaderService.Api/PdfReaderService.Api.csproj", "--urls", "http://0.0.0.0:5047"]