FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

ENV LD_LIBRARY_PATH=/app

# Copiar el código
COPY . .


CMD ["dotnet", "run", "--project", "PdfReaderService.Api/PdfReaderService.Api.csproj", "--urls", "http://0.0.0.0:5047"]
